"""Recovered .eml emitter.

Renders `Event`s carrying an `email` payload as standalone RFC 5322
message files — the kind of artifact a student would recover from a
mailbox export or a user's "save as .eml". One file per event.

Safety note: when `email.has_attachment` is set, this emitter attaches a
clearly-labeled, inert placeholder — never functional macro code, a real
executable, or any live payload. The "original" attachment's declared
sha256 (from the scenario's `FileInfo`/`EmailArtifact`) describes a
*fictional* artifact for the training narrative; it will not match the
hash of the placeholder bytes actually embedded here, and the placeholder
text says so explicitly so nobody mistakes it for the real thing.
"""

from __future__ import annotations

import base64
import mimetypes

from forge_incident.emitters.base import (
    EmittedArtifact,
    Emitter,
    rfc5322_timestamp,
    slugify,
    stable_hex_id,
)
from forge_incident.models import EmailArtifact, LogSource, Scenario

__all__ = ["EmailEmitter"]


class EmailEmitter(Emitter):
    log_source = LogSource.EMAIL_EML

    def emit(self, scenario: Scenario) -> list[EmittedArtifact]:
        events = [e for e in self.relevant_events(scenario) if e.email is not None]
        artifacts: list[EmittedArtifact] = []

        for event in events:
            email = event.email
            assert email is not None
            boundary = stable_hex_id(event.event_id, "mime_boundary", length=24)
            recipients = ", ".join(email.recipients)
            date_header = rfc5322_timestamp(event.timestamp)
            org_domain = scenario.organization.domain

            auth_results = (
                f"spf={email.spf.value} smtp.mailfrom={email.sender}; "
                f"dkim={email.dkim.value} header.d={email.sender.split('@')[-1]}; "
                f"dmarc={email.dmarc.value} header.from={email.sender.split('@')[-1]}"
            )

            received = (
                f"Received: from {_source_host(email.client_ip)} ({email.client_ip or 'unknown'})\n"
                f"        by mail.{org_domain} with ESMTPS id "
                f"{stable_hex_id(event.event_id, 'received', length=12)};\n"
                f"        {date_header}"
            )

            headers = [
                received,
                f"Authentication-Results: mail.{org_domain}; {auth_results}",
                f"From: {email.sender}",
                f"To: {recipients}",
                f"Subject: {email.subject}",
                f"Date: {date_header}",
                f"Message-ID: {email.message_id}",
                "MIME-Version: 1.0",
            ]

            if email.has_attachment:
                headers.append(f'Content-Type: multipart/mixed; boundary="{boundary}"')
                body = _multipart_body(email, boundary)
            else:
                headers.append("Content-Type: text/plain; charset=UTF-8")
                headers.append("Content-Transfer-Encoding: 8bit")
                body = "\n" + (email.body_text or "").strip() + "\n"

            content = "\n".join(headers) + "\n" + body
            suffix = stable_hex_id(event.event_id, "filename", length=8)
            filename = f"{slugify(email.subject)}-{suffix}.eml"

            artifacts.append(
                EmittedArtifact(
                    relative_path=f"logs/email_eml/{filename}",
                    content=content,
                    description=(
                        f"Recovered email: {email.subject!r} ({email.sender} -> {recipients})"
                    ),
                )
            )

        return artifacts


def _source_host(client_ip: str | None) -> str:
    if not client_ip:
        return "unknown-host"
    return f"mail-relay-{client_ip.replace('.', '-').replace(':', '-')}"


def _multipart_body(email: EmailArtifact, boundary: str) -> str:
    text_part = (
        f"--{boundary}\n"
        "Content-Type: text/plain; charset=UTF-8\n"
        "Content-Transfer-Encoding: 8bit\n\n"
        f"{(email.body_text or '').strip()}\n\n"
    )

    placeholder_note = (
        "This is a placeholder file generated by ForgeIncident for security-training "
        "purposes. It intentionally contains no functional macro code, script, or "
        "executable payload. In the scenario narrative, the original (fictional) "
        f"attachment was named {email.attachment_name!r}"
        + (f" with declared SHA-256 {email.attachment_sha256!r}" if email.attachment_sha256 else "")
        + ". That hash describes the fictional artifact for instructor materials; it will "
        "NOT match this inert placeholder's bytes.\n"
    )
    encoded = base64.b64encode(placeholder_note.encode("utf-8")).decode("ascii")
    encoded_lines = "\n".join(encoded[i : i + 76] for i in range(0, len(encoded), 76))

    content_type = (
        mimetypes.guess_type(email.attachment_name or "")[0] or "application/octet-stream"
    )

    attachment_part = (
        f"--{boundary}\n"
        f"Content-Type: {content_type}; name=\"{email.attachment_name}\"\n"
        "Content-Transfer-Encoding: base64\n"
        f"Content-Disposition: attachment; filename=\"{email.attachment_name}\"\n\n"
        f"{encoded_lines}\n\n"
    )

    return text_part + attachment_part + f"--{boundary}--\n"
